---
- name: Install MongoDB
  hosts: n1
  become: true
  vars:
    mongodb_bind_ip: "127.0.0.1"  
    mongodb_port: 27017

  tasks:
    - name: Add MongoDB GPG key
      rpm_key:
        state: present
        key: "https://www.mongodb.org/static/pgp/server-7.0.asc"

    - name: Configure MongoDB 7.0 repo
      yum_repository:
        name: mongodb-org-7.0
        description: MongoDB 7.0 Repository
        baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
        gpgcheck: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-7.0.asc
        enabled: yes

    - name: Install MongoDB packages
      dnf:
        name:
          - mongodb-org
          - mongodb-org-server
          - mongodb-mongosh
        state: present

    - name: Create MongoDB config
      copy:
        dest: /etc/mongod.conf
        content: |
          systemLog:
            destination: file
            path: /var/log/mongodb/mongod.log
            logAppend: true

          storage:
            dbPath: /var/lib/mongo
            journal:
              enabled: true

          net:
            bindIp: {{ mongodb_bind_ip }}
            port: {{ mongodb_port }}

          security:
            authorization: disabled
        owner: root
        group: root
        mode: 0644
      notify: restart mongod

    - name: Ensure MongoDB data directory exists
      file:
        path: /var/lib/mongo
        state: directory
        owner: mongod
        group: mongod
        mode: 0755

    - name: Start and enable MongoDB
      service:
        name: mongod
        state: started
        enabled: yes

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted
...
