---
- name: Deploy Node.js Express with MongoDB App
  hosts: n1
  become: true
  vars:
    app_user: "nodeapp"
    app_dir: "/opt/nodeapp"
    app_repo: "https://github.com/Eniiwinner/mm.git"
    app_branch: "main"
    node_version: "18.x"

  tasks:
    - name: Install MongoDB and dependencies
      dnf:
        name:
          - mongodb-org
          - gcc-c++
          - make
          - git
          - firewalld
        state: present

    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Add NodeSource repository
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }} | bash -
      args:
        creates: "/etc/yum.repos.d/nodesource-el9.repo"

    - name: Install Node.js
      dnf:
        name: nodejs
        state: present

    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        home: "{{ app_dir }}"
        create_home: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0755

    - name: Clone application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        version: "{{ app_branch }}"
        force: yes
      become_user: "{{ app_user }}"

    - name: Install dependencies
      npm:
        path: "{{ app_dir }}"
        state: present
      become_user: "{{ app_user }}"

    - name: Create systemd service
      copy:
        dest: "/etc/systemd/system/nodeapp.service"
        content: |
          [Unit]
          Description=Node.js Express App
          After=network.target mongod.service

          [Service]
          User={{ app_user }}
          WorkingDirectory={{ app_dir }}
          Environment=NODE_ENV=production
          ExecStart=/usr/bin/node {{ app_dir }}/index.js
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      notify:
        - reload systemd
        - restart nodeapp

    - name: Enable and start service
      service:
        name: nodeapp
        state: started
        enabled: yes

    - name: Configure firewall
      block:
        - name: Ensure firewalld is running
          service:
            name: firewalld
            state: started
            enabled: yes

        - name: Open port 3000
          command: firewall-cmd --permanent --add-port=3000/tcp
          register: firewall_result
          changed_when: "'success' in firewall_result.stdout"

        - name: Reload firewall
          command: firewall-cmd --reload
          when: firewall_result is changed

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart nodeapp
      service:
        name: nodeapp
        state: restarted
...