---
- name: Install and Configure MongoDB 8.0
  hosts: n1
  become: true
  vars:
    mongodb_bind_ip: "127.0.0.1"
    mongodb_port: 27017
    mongodb_data_dir: "/var/lib/mongo"
    mongodb_log_dir: "/var/log/mongodb"

  tasks:
    - name: Add MongoDB 8.0 GPG key
      rpm_key:
        state: present
        key: "https://www.mongodb.org/static/pgp/server-8.0.asc"

    - name: Configure MongoDB 8.0 repository
      yum_repository:
        name: mongodb-org-8.0
        description: MongoDB 8.0 Repository
        baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/8.0/x86_64/
        gpgcheck: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-8.0.asc
        enabled: yes

    - name: Install MongoDB 8.0
      dnf:
        name:
          - mongodb-org
          - mongodb-org-server
          - mongodb-org-mongos
          - mongodb-mongosh
          - mongodb-database-tools
        state: present

    - name: Create MongoDB data directory
      file:
        path: "{{ mongodb_data_dir }}"
        state: directory
        owner: mongod
        group: mongod
        mode: 0755

    - name: Create MongoDB log directory
      file:
        path: "{{ mongodb_log_dir }}"
        state: directory
        owner: mongod
        group: mongod
        mode: 0755

    - name: Create MongoDB configuration
      copy:
        dest: /etc/mongod.conf
        content: |
          systemLog:
            destination: file
            path: {{ mongodb_log_dir }}/mongod.log
            logAppend: true
            logRotate: reopen

          storage:
            dbPath: {{ mongodb_data_dir }}
            engine: wiredTiger
            journal:
              enabled: true

          net:
            bindIp: {{ mongodb_bind_ip }}
            port: {{ mongodb_port }}
            ipv6: false

          processManagement:
            fork: true
            pidFilePath: /var/run/mongodb/mongod.pid
            timeZoneInfo: /usr/share/zoneinfo

          security:
            authorization: disabled
            javascriptEnabled: true
        owner: root
        group: root
        mode: 0644
      notify: restart mongod

    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Verify MongoDB version
      command: mongod --version
      register: mongo_version
      changed_when: false

    - name: Display MongoDB version
      debug:
        var: mongo_version.stdout_lines

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted
...