---
- name: Deploy Node.js Express App
  hosts: n1
  become: true
  vars:
    app_user: "nodeapp"
    app_dir: "/opt/nodeapp"
    app_repo: "https://github.com/Eniiwinner/mm.git"
    app_branch: "main"
    node_version: "18.x"

  tasks:
    - name: Install Node.js prerequisites
      dnf:
        name:
          - gcc-c++
          - make
          - git
        state: present

    - name: Add NodeSource repository
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }} | bash -
      args:
        creates: "/etc/yum.repos.d/nodesource-el9.repo"

    - name: Install Node.js and npm
      dnf:
        name:
          - nodejs
        state: present

    - name: Create application user with home directory
      user:
        name: "{{ app_user }}"
        system: yes
        home: "/home/{{ app_user }}"
        create_home: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0755

    - name: Set npm config to use app directory
      shell: |
        mkdir -p {{ app_dir }}/.npm
        npm config set prefix "{{ app_dir }}/.npm"
      become_user: "{{ app_user }}"
      environment:
        HOME: "{{ app_dir }}"

    - name: Clone application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        version: "{{ app_branch }}"
        force: yes
      become_user: "{{ app_user }}"

    - name: Install dependencies
      npm:
        path: "{{ app_dir }}"
        state: present
      become_user: "{{ app_user }}"
      environment:
        npm_config_cache: "{{ app_dir }}/.npm"
        npm_config_prefix: "{{ app_dir }}/.npm"

    - name: Configure systemd service
      template:
        src: nodeapp.service.j2
        dest: "/etc/systemd/system/nodeapp.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload systemd
        - restart nodeapp

    - name: Enable and start service
      service:
        name: nodeapp
        state: started
        enabled: yes

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart nodeapp
      service:
        name: nodeapp
        state: restarted
...